/* Generated By:JJTree: Do not edit this line. ASTFactor.java */

public class ASTFactor extends SimpleNode {

  public int value;

  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Postfix p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PostfixVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
