/* Generated By:JJTree: Do not edit this line. ASTTerm.java */

public class ASTTerm extends SimpleNode {

  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(Postfix p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PostfixVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
