/* Generated By:JavaCC: Do not edit this line. LiteralsSkipConstants.java */
public interface LiteralsSkipConstants {

  int EOF = 0;
  int HELLO = 2;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"hello\"",
  };

}
