/* Generated By:JavaCC: Do not edit this line. LiteralsConstants.java */
public interface LiteralsConstants {

  int EOF = 0;
  int HELLO = 1;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"hello\"",
  };

}
